# Generated by Django 2.2.1 on 2019-06-05 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='WordGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inProgress', models.BooleanField(default=False)),
                ('endTime', models.DateTimeField(null=True)),
                ('board', models.CharField(max_length=5000)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
