# Generated by Django 2.2.1 on 2019-06-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20190605_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
