# Generated by Django 2.2.1 on 2019-07-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20190701_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
