# Generated by Django 2.2.1 on 2019-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20190804_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='in_progress',
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
